synchronize:
  paths:
    - source: .
      exclude:
        - "locales/*"
        - "bin/*"

pretranslate:
  paths:
    - source: .
      include:
        - "README.md"
        - "config/*"
        - "check_one.md"
        - "lalala.md"